### ISSUE TITLE
Classification-banner is available as an active Application and shows in Application Menu Bar to be closable

### ISSUE THREAD

**Issue by clndwhr** [SecurityCentral/classification-banner#1]
OS: RHEL 8.5
Desktop Environment: Wayland Gnome3
Python 3.6
classification-banner-1.7.1

The classification banner presents itself to the user as an active application that can be closed via the application menu. This is an undesirable behavior and after some research it appears the use of the Gtk.Application Class/Interface could provide an option to disable.  I am not familiar enough with python to take on this task.  As a "work around" we have removed Wayland Display server as an option for Gnome desktop environment and am forcing X11 which does not contain this same issue.

**Comment by jegeland** [comment]
@clndwhr, I think this project is OBE for EL8 with the creation of the `gnome-shell-extension-classification-banner.noarch` package from appstream.  It doesn't allow you to hide the class bar with `esc` but you can click *through* the bar anyway.

**Comment by redhatrises** [comment]
Yeah. Using native extensions is the best way to go.

Closing. Feel free to reopen if necessary.
