### ISSUE TITLE
invalid monitors changed notification

### ISSUE THREAD

**Issue by dhyams** [SecurityCentral/classification-banner#12]
In banner.py, line 311, it reads

self.monitor.connet("monitors-changed", self.resize)

surely that is supposed to be "connect"?

**Comment by shawndwells** [comment]
Good catch. Can you submit a quick PR?

**Comment by bracketttc** [comment]
My PR fixes the typo, but the event doesn't appear to fire or cover the case that I thought would test it.

Testing was on Fedora 38, opened and closed the lid of my docked laptop. The laptop screen was added to the active display and desktop extended to it and then that display was removed. At no point did a debug print placed in the `resize` function appear in the console.

Edit: GTK's `monitors-changed` event only works with X11 and whatever OS X's display manager. I'm probably using Wayland on that machine.
